# Generated by Django 2.0.2 on 2018-02-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Organizarion number')),
                ('org_name', models.CharField(max_length=100)),
                ('last_visited', models.DateTimeField(auto_now=True)),
                ('n_visits', models.IntegerField(default=0)),
            ],
        ),
    ]
